version: "3"
services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./Backend/db:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: 'mysql --user=root --password=password --execute "SHOW DATABASES;"'
      timeout: 10s
      retries: 2

  flask_app:
    build: ./Backend/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"

  nodejs_app:
    build:
      context: ./Frontend
    ports:
      - "8000:8000"
    depends_on:
      - flask_app
