version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

  db:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
